// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { A } from "../../bindings/A";
import type { B } from "../../bindings/B";
import type { C } from "./C";

export interface ABC { a: A, b: B, c: C, }